### ISSUE TITLE
Grant klahnakoski ownership to pypi?

### ISSUE THREAD

**Issue by klahnakoski** [doraproject/mo-sql-parsing#11]
Good day!  I see you are using the `mo-sql-parsing` name on pypi.  Would you be so kind to grant me ownership of the project? You can do that here: https://pypi.org/project/mo-sql-parsing/collaboration/

I have finished a milestone on the project, and merged others pull requests, including yours**.  I am now available to release.  I am https://pypi.org/user/klahnakoski/  on pypi

** with a small change: please see https://github.com/doraproject/mo-sql-parsing/issues/6

**Comment by Didone** [comment]
Hi @klahnakoski, glad to meet you! 
No problems at all. I will change some dependencies references and as soon as possible I change the ownership to you (possibly today).
After that will send you an pull request, from my repository with our issues. If it ok for you?
> And yes, I checking with the team about the #6 . Thank you for helping us and will be an honor contribute to your project.

**Comment by klahnakoski** [comment]
@Didone   Thank you very much for your kindness.

> After that will send you an pull request, from my repository with our issues. If it ok for you?

I am absolutely glad to help extend this parser to cover more SQL variants.

>  I will change some dependencies references and as soon as possible

I may need some time to understand your dependencies to ensure the mo-sql-parsing stays compatible with your release process.  I am not currently using poetry, and I am unsure if you require `pyproject.toml` artifact for your CI

**Comment by Didone** [comment]
@klahnakoski I sent you an invite to be owner of the project
https://pypi.org/manage/project/mo-sql-parsing/collaboration/

> I may need some time to understand your dependencies to ensure the mo-sql-parsing stays compatible with your release process. I am not currently using poetry, and I am unsure if you require pyproject.toml artifact for your CI

Don't worry about, here is where we are using `mo-sql-parsing` as dependency: [dora-parse](https://pypi.org/project/dora-parser/)  (the GitHub repository is private right now, but in a few weeks will be public too).

The `dora-parser` helps users in the assessment process for migration projects from some query engines such Apache Impala, and Hive to Spark SQL, Presto, Trino and Athena.

**Comment by klahnakoski** [comment]
Again, thank you very much.  I will be releasing in a few hours.
