### ISSUE TITLE
Add equality operator

### ISSUE THREAD

**Issue by cbonafin** [doraproject/mo-sql-parsing#6]
***Problem***
Mo-sql-parser don't parse, <==>, one of the equality operators of Hive

***Solution***
Add operator into the parser.

**Comment by klahnakoski** [comment]
@Didone  I am having difficulty finding this operator.  I did find `<=>` at https://sparkbyexamples.com/apache-hive/hive-relational-arithmetic-logical-operators/  , which is a very nice operator

**Comment by klahnakoski** [comment]
..technically  `=` and `<=>`  are different.  SQL `=` has behaviour unlike most procedural languages, while `<=>` is much better.  Can  we even call `=` "eq"?  Hmmm.
